framework:
  - terraform
  - terraform_plan

download-external-modules: true
evaluate-variables: true

output:
  - cli
  - json

output_file_path:
  - reports

quiet: false

compact: true

directory:
  - terraform/

skip_check:
  - CKV_AWS_79
  - CKV_AWS_20
  - CKV_AWS_23