framework:
  - terraform
  - terraform_plan

download-external-modules: true
evaluate-variables: true

output:
  - cli
  - json

output-file-path: reports

quiet: false

compact: true

directory:
  - terraform/

skip-check:
  - CKV_AWS_79
  - CKV_AWS_20
  - CKV_AWS_23
  - CKV_AWS_260
  - CKV_AWS_88
  - CKV_AWS_130
  - CKV2_AWS_11
  - CKV2_AWS_41