framework:
  - terraform
  - terraform_plan

download-external-modules: true
evaluate-variables: true

output:
  - cli
  - json

quiet: false

compact: true

directory:
  - terraform/

severity:
  - critical
  - high
  - medium

check:
  # Focus on essential security checks
  - CKV_AWS_8    # Ensure all data stored in the Launch configuration EBS is securely encrypted at rest
  - CKV_AWS_126  # Ensure that detailed monitoring is enabled for EC2 instances
  - CKV_AWS_135  # Ensure that EC2 is EBS optimized
  - CKV_AWS_24   # Ensure no security groups allow ingress from 0.0.0.0:0 to port 22
  - CKV_AWS_25   # Ensure no security groups allow ingress from 0.0.0.0:0 to port 3389