framework:
  - terraform
  - secrets

download-external-modules: true
evaluate-variables: true

# Skip specific checks if needed (reduced list)
skip-check:
  # Skip checks that might be acceptable for development environment
  - CKV_AWS_23  # Security group descriptions (already implemented)

# Directories to scan
directory:
  - terraform/

# Output format
output: cli

# Severity threshold - include all levels for comprehensive scanning
check:
  - HIGH
  - MEDIUM
  - LOW

# Generate reports
output-file-path: reports/checkov-report.json
output-format: json,cli

# Enable additional checks
enable-secrets-scan-all-files: true